# 定义 stages
stages:
  - build
  - test
  - deploy
#  - apibuild

variables:
  LS_CMD: 'ls $FLAGS $$TMP_DIR'
  FLAGS: '-al'
  FLAGST: 'echo $CI_RUNNER_ID'
  MY_CI_REGISTRY_IMAGE: 192.168.9.69:5000/${CI_PROJECT_NAME}:$CI_BUILD_TAG
  MY_MARATHON_URL: 192.168.9.61:8080
# 定义编译阶段
build_stages:
  stage: build
  script:

    - export
    - docker
#    - docker build -t $TEST_CI_REGISTRY_IMAGE .
    - if [ "$CI_BUILD_TAG" ]; then  docker build -t $MY_CI_REGISTRY_IMAGE .;fi
    
#    - if [ -n "${PUSH_TO_REGISTRY}" ]; then docker build -t $MY_CI_REGISTRY_IMAGE .;fi
  tags:
    - dockerin
# 定义测试阶段
test_stages:
  tags:
    - dockerin
  stage: test
  script:
    - cd code/bpm
#    - code mocha
#    - echo "TEST"
#    - echo "test stage"

# 定义部署阶段
release_image:
  tags:
    - dockerin
  stage: deploy
  script:
#    - ping -c 5 117.187.12.236
    - ping -c 5 192.168.9.69
    - if [ "$CI_BUILD_TAG" ]; then docker push $MY_CI_REGISTRY_IMAGE ;fi

    
