image: 218.201.251.104:15000/library/docker:git

variables:
  #Changlog路径
  CHANGLOG: "./changelog.txt"
  # 镜像库URL
  DOCKER_REG: "218.201.251.104:15000"
  # 最新版(latest)镜像地址
  IMAGE_LATEST: "$DOCKER_REG/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest"
  # 发行版(带版本号)镜像地址
  IMAGE_RELASE: "$DOCKER_REG/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG"
  # Beta版(beta)镜像地址
  IMAGE_BETA: "$DOCKER_REG/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:beta"
  # Stable版(stable)镜像地址
  IMAGE_STABLE: "$DOCKER_REG/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:stable"

before_script:
  - $DOCKER_LOGIN
   
after_script:
  - $DOCKER_LOGOUT

latest_build_image:
  stage: build
  script:
    - echo $IMAGE_LATEST
    - echo "PROJECT:$CI_PROJECT_PATH"  > $CHANGLOG
    - echo "BRANCH_NAME:$CI_COMMIT_REF_NAME"  >> $CHANGLOG
    - echo "IMAGE VERSION:latest" >> $CHANGLOG
    - echo "COMMIT:$CI_COMMIT_SHA"  >> $CHANGLOG
    - echo "BUILD_ID:$CI_BUILD_ID"  >> $CHANGLOG
    - date "+BUILD_DATE :%Y-%m-%d %H:%M:%S"   >> $CHANGLOG
    - echo "CHANGE_LOG" >>$CHANGLOG
    - git log  --graph >> $CHANGLOG
    - cat $CHANGLOG
    - docker build --no-cache --label version="latest" -t $IMAGE_LATEST .
  only:
    - master
  
latest_push_image:
  stage: build
  script:
    - echo $IMAGE_LATEST
    - docker push $IMAGE_LATEST
    - docker push $IMAGE_LATEST
  only:
    - master

stable_build_image:
  stage: build
  script:
    - echo $IMAGE_RELASE
    - echo $IMAGE_STABLE
    - echo "PROJECT:$CI_PROJECT_PATH"  > $CHANGLOG
    - echo "IMAGE VERSION:stable" >> $CHANGLOG
    - echo "IMAGE RELEASE VERSION:$CI_COMMIT_TAG" >> $CHANGLOG
    - echo "BRANCH_NAME:$CI_COMMIT_REF_NAME"  >> $CHANGLOG
    - echo "COMMIT:$CI_COMMIT_SHA"  >> $CHANGLOG
    - echo "BUILD_ID:$CI_BUILD_ID"  >> $CHANGLOG
    - date "+BUILD_DATE :%Y-%m-%d %H:%M:%S"   >> $CHANGLOG
    - echo "CHANGE LOG" >>$CHANGLOG
    - git log  --graph >> $CHANGLOG
    - cat $CHANGLOG
    - docker build --no-cache --label version="relase tag" -t $IMAGE_RELASE .
    - docker build --no-cache --label version="stable" -t $IMAGE_STABLE .

  only:
    - /^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{0,1}[0|2|4|6|8].[0-9]{9}$/
  except:
    - dev

stable_push_image:
  stage: build
  script:
    - echo $IMAGE_RELASE
    - echo $IMAGE_STABLE
    - docker push $IMAGE_RELASE
    - docker push $IMAGE_RELASE
    - docker push $IMAGE_STABLE
    - docker push $IMAGE_STABLE
  only:
    - /^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{0,1}[0|2|4|6|8].[0-9]{9}$/
  except:
    - dev


beta_build_image:
  stage: build
  script:
    - echo $IMAGE_RELASE
    - echo $IMAGE_BETA
    - echo "PROJECT:$CI_PROJECT_PATH"  > $CHANGLOG
    - echo "IMAGE VERSION:beta" >> $CHANGLOG
    - echo "IMAGE RELEASE VERSION:$CI_COMMIT_TAG" >> $CHANGLOG    
    - echo "BRANCH_NAME:$CI_COMMIT_REF_NAME"  >> $CHANGLOG
    - echo "COMMIT:$CI_COMMIT_SHA"  >> $CHANGLOG
    - echo "BUILD_ID:$CI_BUILD_ID"  >> $CHANGLOG
    - date "+BUILD_DATE :%Y-%m-%d %H:%M:%S"   >> $CHANGLOG
    - echo "CHANGE LOG" >>$CHANGLOG
    - git log  --graph >> $CHANGLOG
    - cat $CHANGLOG
    - docker build --no-cache --label version="relase tag" -t $IMAGE_RELASE .
    - docker build --no-cache --label version="beta" -t $IMAGE_BETA .
  only:
    - /^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{0,1}[1|3|5|7|9].[0-9]{9}$/
  except:
    - dev

beta_push_image:
  stage: build
  script:
    - echo $IMAGE_RELASE
    - echo $IMAGE_BETA
    - docker push $IMAGE_RELASE
    - docker push $IMAGE_RELASE
    - docker push $IMAGE_BETA
    - docker push $IMAGE_BETA
  only:
    - /^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{0,1}[1|3|5|7|9].[0-9]{9}$/
  except:
    - dev 


latest_deploy:
  stage: deploy
  script:
    - curl -s -XDELETE http://10.196.130.89:8080/v2/apps/projects/gdgl/pm
    - 'curl -s -XPOST -H "Content-Type: application/json" http://10.196.130.89:8080/v2/apps?force=true -d @marathon.json'    
  only:
    - master  

